Task4: Db connection, Entity framework
Dezzelshipc/HospitalProjectIT pull request #4
Opened 2022-11-12 06:07 UTC by Dezzelshipc

2022-11-12 06:44 UTC, Vixorem commented on Database/ApplicationContext.cs
> +            modelBuilder.Entity<UserModel>().HasKey(model => model.Id);
А зачем индекс на каждое поле

2022-11-12 06:44 UTC, Vixorem commented on Database/ApplicationContext.cs
> +
Ну вроде бы на Id не нужны индексы потому что Id будет и так primary key

2022-11-12 06:44 UTC, Vixorem commented on Database/Migrations/20221112055942_Test1.cs
> +    public partial class Test1 : Migration
Название миграции не самое выразительное, но да ладно)

2022-11-12 06:48 UTC, Dezzelshipc commented on Database/ApplicationContext.cs
> +            modelBuilder.Entity<UserModel>().HasKey(model => model.Id);
В бд просто не появлялись поля, которые не указаны. И, например, во всех других таблицах сейчас есть только поле id

2022-11-12 09:12 UTC, 8Vinso8 commented on Database/Converters/DomainModelAppointmentConverter.cs
> +        public static Appointment ToDomian(this AppointmentModel model)
Опечатка

2022-11-12 09:20 UTC, 8Vinso8 commented on Database/Converters/DomainModelDoctorConverter.cs
> +        public static Doctor ToDomian(this DoctorModel model)
Опечатка

2022-11-12 09:22 UTC, 8Vinso8 commented on Database/Converters/DomainModelScheduleConverter.cs
> +        public static Schedule ToDomian(this ScheduleModel model)
опечатка

2022-11-12 09:22 UTC, 8Vinso8 commented on Database/Converters/DomianModelSpecializationConverter.cs
> +        public static Specialization ToDomian(this SpecializationModel model)
Опечатка

2022-11-12 09:33 UTC, 8Vinso8 requested changes
Исправить опечатки

2022-11-12 09:40 UTC, Vixorem commented on Database/ApplicationContext.cs
> +            modelBuilder.Entity<UserModel>().HasKey(model => model.Id);
Хм. А попробуйте знаете что, заменить все поля на автосвойства. Это которые с {get; set;}
Типа public int Id {get; set;}

2022-11-12 12:11 UTC, 8Vinso8 approved these changes

2022-11-12 12:11 UTC, 8Vinso8 commented on Database/ApplicationContext.cs
> +        public DbSet<ScheduleModel> Schedlues { get; set; }
Опечатка

2022-11-13 00:56 UTC, Vixorem approved these changes

2022-11-13 01:29 UTC, merged