Task 5: User http endpoints
Dezzelshipc/HospitalProjectIT pull request #5
Opened 2022-12-21 05:11 UTC by Dezzelshipc

2022-12-26 10:04 UTC, Vixorem requested changes

2022-12-26 10:04 UTC, Vixorem commented on HospitalProjectIT/Controllers/UserController.cs
> +    [Route("user")]
Недостаточно просто склонить проект с моего гита. В задании написано, что надо реализовать все контроллеры. Даже для контроллера юзера у вас не все методы

2022-12-29 03:34 UTC, Vixorem commented
Нормас

2022-12-29 03:34 UTC, Vixorem approved these changes

2022-12-29 04:10 UTC, 8Vinso8 approved these changes

2022-12-29 12:23 UTC, merged