Task6: Mutex, JWT Token
Dezzelshipc/HospitalProjectIT pull request #6
Opened 2023-01-07 16:28 UTC by Dezzelshipc

2023-01-07 16:35 UTC, 8Vinso8 approved these changes

2023-01-08 11:21 UTC, Vixorem requested changes

2023-01-08 11:21 UTC, Vixorem commented on HospitalProjectIT/Controllers/AppointmentController.cs
> +            _mutexSave.WaitOne();
Ага. Ништяк. А теперь давай подумаем, как это можно оптимизировать. Сейчас на каждый запрос будет происходить блокировка. А что если мы записываемся к разным врачам, есть ли смысл в блокировке?

2023-01-08 11:21 UTC, Vixorem commented on HospitalProjectIT/Controllers/DoctorController.cs
> +            _mutexCreate.WaitOne();
Не, погоди. Мьютекс решает проблему того, чтобы у нас с точки зрения процесса записи на прием не было неприятных ситуаций, типа, когда к одному врачу записались разные пациенты. Не нужно пихать мьютексы во все методы

2023-01-08 11:21 UTC, Vixorem commented on HospitalProjectIT/Controllers/AppointmentController.cs
> +            _mutexSave.WaitOne();
А еще это не должно быть в слое контроллера

2023-01-10 11:36 UTC, Vixorem approved these changes

2023-01-11 10:11 UTC, merged